module.exports = [
    {
        city: "Sofia", 
        latitude: "42.6975", 
        longitude: "23.3241", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia-Grad", 
        capital: "primary", 
        population: "1355142", 
        population_proper: "1355142",
        rank: "1",
    }, 
    {
        city: "Plovdiv", 
        latitude: "42.1433", 
        longitude: "24.7489", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "admin", 
        population: "384088", 
        population_proper: "384088",
        rank: "2",
    }, 
    {
        city: "Varna", 
        latitude: "43.2078", 
        longitude: "27.9169", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "admin", 
        population: "369162", 
        population_proper: "369162",
        rank: "3",
    }, 
    {
        city: "Burgas", 
        latitude: "42.5000", 
        longitude: "27.4667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "admin", 
        population: "226868", 
        population_proper: "226868",
        rank: "4",
    }, 
    {
        city: "Ruse", 
        latitude: "43.8475", 
        longitude: "25.9544", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "admin", 
        population: "163712", 
        population_proper: "163712",
        rank: "5",
    }, 
    {
        city: "Stara Zagora", 
        latitude: "42.4247", 
        longitude: "25.6256", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "admin", 
        population: "158668", 
        population_proper: "158668",
        rank: "6",
    }, 
    {
        city: "Pleven", 
        latitude: "43.4078", 
        longitude: "24.6203", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "admin", 
        population: "123588", 
        population_proper: "123588",
        rank: "7",
    }, 
    {
        city: "Sliven", 
        latitude: "42.6808", 
        longitude: "26.3164", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sliven", 
        capital: "admin", 
        population: "107570", 
        population_proper: "107570",
        rank: "8",
    }, 
    {
        city: "Dobrich", 
        latitude: "43.5667", 
        longitude: "27.8333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "admin", 
        population: "104530", 
        population_proper: "104530",
        rank: "9",
    }, 
    {
        city: "Shumen", 
        latitude: "43.2700", 
        longitude: "26.9244", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "admin", 
        population: "97719", 
        population_proper: "97719",
        rank: "10",
    }, 
    {
        city: "Haskovo", 
        latitude: "41.9311", 
        longitude: "25.5575", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "admin", 
        population: "93821", 
        population_proper: "93821",
        rank: "11",
    }, 
    {
        city: "Pazardzhik", 
        latitude: "42.1892", 
        longitude: "24.3317", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "admin", 
        population: "84619", 
        population_proper: "84619",
        rank: "12",
    }, 
    {
        city: "Yambol", 
        latitude: "42.4844", 
        longitude: "26.5086", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Yambol", 
        capital: "admin", 
        population: "84232", 
        population_proper: "84232",
        rank: "13",
    }, 
    {
        city: "Pernik", 
        latitude: "42.6097", 
        longitude: "23.0308", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pernik", 
        capital: "admin", 
        population: "83973", 
        population_proper: "83973",
        rank: "14",
    }, 
    {
        city: "Blagoevgrad", 
        latitude: "42.0219", 
        longitude: "23.0975", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "admin", 
        population: "82606", 
        population_proper: "82606",
        rank: "15",
    }, 
    {
        city: "Veliko Tarnovo", 
        latitude: "43.0822", 
        longitude: "25.6317", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "admin", 
        population: "72207", 
        population_proper: "72207",
        rank: "16",
    }, 
    {
        city: "Vratsa", 
        latitude: "43.2000", 
        longitude: "23.5500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "admin", 
        population: "69493", 
        population_proper: "69493",
        rank: "17",
    }, 
    {
        city: "Kardzhali", 
        latitude: "41.6400", 
        longitude: "25.3708", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "admin", 
        population: "66128", 
        population_proper: "66128",
        rank: "18",
    }, 
    {
        city: "Kyustendil", 
        latitude: "42.2811", 
        longitude: "22.6889", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kyustendil", 
        capital: "admin", 
        population: "63359", 
        population_proper: "63359",
        rank: "19",
    }, 
    {
        city: "Gabrovo", 
        latitude: "42.8711", 
        longitude: "25.3150", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Gabrovo", 
        capital: "admin", 
        population: "62938", 
        population_proper: "62938",
        rank: "20",
    }, 
    {
        city: "Asenovgrad", 
        latitude: "42.0069", 
        longitude: "24.8756", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "59793", 
        population_proper: "59793",
        rank: "21",
    }, 
    {
        city: "Vidin", 
        latitude: "43.9853", 
        longitude: "22.8764", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "admin", 
        population: "58018", 
        population_proper: "58018",
        rank: "22",
    }, 
    {
        city: "Kazanlak", 
        latitude: "42.6167", 
        longitude: "25.4000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "56047", 
        population_proper: "56047",
        rank: "23",
    }, 
    {
        city: "Montana", 
        latitude: "43.4078", 
        longitude: "23.2250", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "admin", 
        population: "49597", 
        population_proper: "49597",
        rank: "24",
    }, 
    {
        city: "Targovishte", 
        latitude: "43.2467", 
        longitude: "26.5719", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Targovishte", 
        capital: "admin", 
        population: "45535", 
        population_proper: "45535",
        rank: "25",
    }, 
    {
        city: "Dimitrovgrad", 
        latitude: "42.0611", 
        longitude: "25.5933", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "45098", 
        population_proper: "45098",
        rank: "26",
    }, 
    {
        city: "Silistra", 
        latitude: "44.1186", 
        longitude: "27.2603", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "admin", 
        population: "42651", 
        population_proper: "42651",
        rank: "27",
    }, 
    {
        city: "Lovech", 
        latitude: "43.1342", 
        longitude: "24.7172", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "admin", 
        population: "42343", 
        population_proper: "42343",
        rank: "28",
    }, 
    {
        city: "Razgrad", 
        latitude: "43.5267", 
        longitude: "26.5242", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Razgrad", 
        capital: "admin", 
        population: "41909", 
        population_proper: "41909",
        rank: "29",
    }, 
    {
        city: "Petrich", 
        latitude: "41.3953", 
        longitude: "23.2069", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "40728", 
        population_proper: "40728",
        rank: "30",
    }, 
    {
        city: "Dupnitsa", 
        latitude: "42.2650", 
        longitude: "23.1178", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kyustendil", 
        capital: "", 
        population: "39467", 
        population_proper: "39467",
    }, 
    {
        city: "Gorna Oryahovitsa", 
        latitude: "43.1222", 
        longitude: "25.6897", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "35031", 
        population_proper: "35031",
    }, 
    {
        city: "Smolyan", 
        latitude: "41.5753", 
        longitude: "24.7128", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "admin", 
        population: "31548", 
        population_proper: "31548",
    }, 
    {
        city: "Sandanski", 
        latitude: "41.5589", 
        longitude: "23.2744", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "30695", 
        population_proper: "30695",
    }, 
    {
        city: "Samokov", 
        latitude: "42.3381", 
        longitude: "23.5600", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "29094", 
        population_proper: "29094",
    }, 
    {
        city: "Nova Zagora", 
        latitude: "42.4903", 
        longitude: "26.0122", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sliven", 
        capital: "", 
        population: "26660", 
        population_proper: "26660",
    }, 
    {
        city: "Karlovo", 
        latitude: "42.6430", 
        longitude: "24.8053", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "25919",
        population_proper: "25919",
    }, 
    {
        city: "Velingrad", 
        latitude: "42.0267", 
        longitude: "23.9910", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "25764", 
        population_proper: "25764",
    }, 
    {
        city: "Sevlievo", 
        latitude: "43.0258", 
        longitude: "25.1039", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Gabrovo", 
        capital: "", 
        population: "25372", 
        population_proper: "25372",
    }, 
    {
        city: "Lom", 
        latitude: "43.8272", 
        longitude: "23.2364", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "25172", 
        population_proper: "25172",
    }, 
    {
        city: "Aytos", 
        latitude: "42.7000", 
        longitude: "27.2500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "24750", 
        population_proper: "24750",
    }, 
    {
        city: "Svishtov", 
        latitude: "43.6186", 
        longitude: "25.3439", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "minor", 
        population: "24459", 
        population_proper: "24459",
    }, 
    {
        city: "Harmanli", 
        latitude: "41.9297", 
        longitude: "25.9019", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "23932", 
        population_proper: "23932",
    }, 
    {
        city: "Troyan", 
        latitude: "42.8844", 
        longitude: "24.7094", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "", 
        population: "23520", 
        population_proper: "23520",
    }, 
    {
        city: "Botevgrad", 
        latitude: "42.9083", 
        longitude: "23.7919", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "22742", 
        population_proper: "22742",
    }, 
    {
        city: "Gotse Delchev", 
        latitude: "41.5728", 
        longitude: "23.7294", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "21969", 
        population_proper: "21969",
    }, 
    {
        city: "Peshtera", 
        latitude: "42.0322", 
        longitude: "24.3022", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "21824", 
        population_proper: "21824",
    }, 
    {
        city: "Karnobat", 
        latitude: "42.6500", 
        longitude: "26.9833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "20411", 
        population_proper: "20411",
    }, 
    {
        city: "Svilengrad", 
        latitude: "41.7675", 
        longitude: "26.1975", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "20390", 
        population_proper: "20390",
    }, 
    {
        city: "Momchilgrad", 
        latitude: "41.5272", 
        longitude: "25.4075", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "", 
        population: "19609", 
        population_proper: "19609",
    }, 
    {
        city: "Panagyurishte", 
        latitude: "42.5047", 
        longitude: "24.1892", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "18350", 
        population_proper: "18350",
    }, 
    {
        city: "Popovo", 
        latitude: "43.3481", 
        longitude: "26.2275", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Targovishte", 
        capital: "", 
        population: "17703", 
        population_proper: "17703",
    }, 
    {
        city: "Chirpan", 
        latitude: "42.1994", 
        longitude: "25.3242", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "17522", 
        population_proper: "17522",
    }, 
    {
        city: "Rakovski", 
        latitude: "42.2875", 
        longitude: "24.9678", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "16731", 
        population_proper: "16731",
    }, 
    {
        city: "Parvomay", 
        latitude: "42.0994", 
        longitude: "25.2242", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "15518", 
        population_proper: "15518",
    }, 
    {
        city: "Provadia", 
        latitude: "43.1789", 
        longitude: "27.4431", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "15095", 
        population_proper: "15095",
    }, 
    {
        city: "Berkovitsa", 
        latitude: "43.2361", 
        longitude: "23.1258", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "14993", 
        population_proper: "14993",
    }, 
    {
        city: "Novi Pazar", 
        latitude: "43.3500", 
        longitude: "27.2000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "", 
        population: "14931", 
        population_proper: "14931",
    }, 
    {
        city: "Radomir", 
        latitude: "42.5467", 
        longitude: "22.9642", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pernik", 
        capital: "", 
        population: "14880", 
        population_proper: "14880",
    }, 
    {
        city: "Ihtiman", 
        latitude: "42.4333", 
        longitude: "23.8167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "14656", 
        population_proper: "14656",
    }, 
    {
        city: "Pomorie", 
        latitude: "42.5586", 
        longitude: "27.6417", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "minor", 
        population: "14634", 
        population_proper: "14634",
    }, 
    {
        city: "Novi Iskar", 
        latitude: "42.8031", 
        longitude: "23.3436", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia-Grad", 
        capital: "", 
        population: "13768", 
        population_proper: "13768",
    }, 
    {
        city: "Nesebar", 
        latitude: "42.6608", 
        longitude: "27.7139", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "minor", 
        population: "13559", 
        population_proper: "13559",
    }, 
    {
        city: "Radnevo", 
        latitude: "42.2886", 
        longitude: "25.9336", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "13554", 
        population_proper: "13554",
    }, 
    {
        city: "Balchik", 
        latitude: "43.4078", 
        longitude: "28.1622", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "13393", 
        population_proper: "13393",
    }, 
    {
        city: "Razlog", 
        latitude: "41.8853", 
        longitude: "23.4667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "13158", 
        population_proper: "13158",
    }, 
    {
        city: "Byala Slatitudeina", 
        latitude: "43.4667", 
        longitude: "23.9333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "", 
        population: "12935", 
        population_proper: "12935",
    }, 
    {
        city: "Kozloduy", 
        latitude: "43.7781", 
        longitude: "23.7275", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "minor", 
        population: "12400", 
        population_proper: "12400",
    }, 
    {
        city: "Kavarna", 
        latitude: "43.4333", 
        longitude: "28.3389", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "12369", 
        population_proper: "12369",
    }, 
    {
        city: "Stamboliyski", 
        latitude: "42.1344", 
        longitude: "24.5353", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "12346", 
        population_proper: "12346",
    }, 
    {
        city: "Pavlikeni", 
        latitude: "43.2367", 
        longitude: "25.3092", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "11921", 
        population_proper: "11921",
    }, 
    {
        city: "Isperih", 
        latitude: "43.7156", 
        longitude: "26.8275", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Razgrad", 
        capital: "", 
        population: "11797", 
        population_proper: "11797",
    }, 
    {
        city: "Mezdra", 
        latitude: "43.1425", 
        longitude: "23.7142", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "", 
        population: "11719", 
        population_proper: "11719",
    }, 
    {
        city: "Kostinbrod", 
        latitude: "42.8167", 
        longitude: "23.2167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "11430", 
        population_proper: "11430",
    }, 
    {
        city: "Etropole", 
        latitude: "42.8333", 
        longitude: "24.0000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "11292", 
        population_proper: "11292",
    }, 
    {
        city: "Bankya", 
        latitude: "42.7000", 
        longitude: "23.1333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia-Grad", 
        capital: "", 
        population: "11233", 
        population_proper: "11233",
    }, 
    {
        city: "Knezha", 
        latitude: "43.5000", 
        longitude: "24.0833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "minor", 
        population: "11124", 
        population_proper: "11124",
    }, 
    {
        city: "Elhovo", 
        latitude: "42.1719", 
        longitude: "26.5658", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Yambol", 
        capital: "", 
        population: "10929", 
        population_proper: "10929",
    }, 
    {
        city: "Omurtag", 
        latitude: "43.1072", 
        longitude: "26.4192", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Targovishte", 
        capital: "", 
        population: "10825", 
        population_proper: "10825",
    }, 
    {
        city: "Tutrakan", 
        latitude: "44.0481", 
        longitude: "26.6044", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "minor", 
        population: "10370", 
        population_proper: "10370",
    }, 
    {
        city: "Ardino", 
        latitude: "41.5833", 
        longitude: "25.1333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "", 
        population: "10336", 
        population_proper: "10336",
    }, 
    {
        city: "Lukovit", 
        latitude: "43.2061", 
        longitude: "24.1631", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "", 
        population: "10316", 
        population_proper: "10316",
    }, 
    {
        city: "Teteven", 
        latitude: "42.9167", 
        longitude: "24.2667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "", 
        population: "10279", 
        population_proper: "10279",
    }, 
    {
        city: "Kubrat", 
        latitude: "43.7967", 
        longitude: "26.5011", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Razgrad", 
        capital: "minor", 
        population: "10011", 
        population_proper: "10011",
    }, 
    {
        city: "Tryavna", 
        latitude: "42.8667", 
        longitude: "25.4919", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Gabrovo", 
        capital: "", 
        population: "9634", 
        population_proper: "9634",
    }, 
    {
        city: "Bansko", 
        latitude: "41.8333", 
        longitude: "23.4833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "9497", 
        population_proper: "9497",
    }, 
    {
        city: "Sredets", 
        latitude: "42.3461", 
        longitude: "27.1808", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "9237", 
        population_proper: "9237",
    }, 
    {
        city: "Veliki Preslav", 
        latitude: "43.1614", 
        longitude: "26.8125", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "", 
        population: "9196", 
        population_proper: "9196",
    }, 
    {
        city: "Krichim", 
        latitude: "42.0414", 
        longitude: "24.4700", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "9188", 
        population_proper: "9188",
    }, 
    {
        city: "Devnya", 
        latitude: "43.2189", 
        longitude: "27.5603", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "9036", 
        population_proper: "9036",
    }, 
    {
        city: "Rakitovo", 
        latitude: "41.9900", 
        longitude: "24.0872", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "8977", 
        population_proper: "8977",
    }, 
    {
        city: "Septemvri", 
        latitude: "42.2183", 
        longitude: "24.1237", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "8813", 
        population_proper: "8813",
    }, 
    {
        city: "Krumovgrad", 
        latitude: "41.4719", 
        longitude: "25.6528", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "minor", 
        population: "8800", 
        population_proper: "8800",
    }, 
    {
        city: "Lyaskovets", 
        latitude: "43.1061", 
        longitude: "25.7153", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "8728", 
        population_proper: "8728",
    }, 
    {
        city: "Simeonovgrad", 
        latitude: "42.0344", 
        longitude: "25.8319", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "8539", 
        population_proper: "8539",
    }, 
    {
        city: "Dzhebel", 
        latitude: "41.5000", 
        longitude: "25.3000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "minor", 
        population: "8514", 
        population_proper: "8514",
    }, 
    {
        city: "Dulovo", 
        latitude: "43.8225", 
        longitude: "27.1406", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "", 
        population: "8493", 
        population_proper: "8493",
    }, 
    {
        city: "Aksakovo", 
        latitude: "43.2592", 
        longitude: "27.8175", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "8164", 
        population_proper: "8164",
    }, 
    {
        city: "Belene", 
        latitude: "43.6456", 
        longitude: "25.1258", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "minor", 
        population: "8122", 
        population_proper: "8122",
    }, 
    {
        city: "Beloslav", 
        latitude: "43.1892", 
        longitude: "27.7050", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "minor", 
        population: "8017", 
        population_proper: "8017",
    }, 
    {
        city: "Svoge", 
        latitude: "42.9594", 
        longitude: "23.3477", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "8003", 
        population_proper: "8003",
    }, 
    {
        city: "Dryanovo", 
        latitude: "42.9736", 
        longitude: "25.4747", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Gabrovo", 
        capital: "", 
        population: "7908", 
        population_proper: "7908",
    }, 
    {
        city: "Lyubimets", 
        latitude: "41.8333", 
        longitude: "26.0833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "7892", 
        population_proper: "7892",
    }, 
    {
        city: "Tervel", 
        latitude: "43.7500", 
        longitude: "27.4000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "7632", 
        population_proper: "7632",
    }, 
    {
        city: "Zlatitudeograd", 
        latitude: "41.3797", 
        longitude: "25.0928", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "7623", 
        population_proper: "7623",
    }, 
    {
        city: "Dolni Chiflik", 
        latitude: "42.9931", 
        longitude: "27.7158", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "7557", 
        population_proper: "7557",
    }, 
    {
        city: "Simitli", 
        latitude: "41.8919", 
        longitude: "23.1111", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "7372", 
        population_proper: "7372",
    }, 
    {
        city: "Pirdop", 
        latitude: "42.7000", 
        longitude: "24.1833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "7353", 
        population_proper: "7353",
    }, 
    {
        city: "Kuklen", 
        latitude: "42.0353", 
        longitude: "24.7853", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "7331", 
        population_proper: "7331",
    }, 
    {
        city: "Slivnitsa", 
        latitude: "42.8522", 
        longitude: "23.0375", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "minor", 
        population: "7320", 
        population_proper: "7320",
    }, 
    {
        city: "Elin Pelin", 
        latitude: "42.6689", 
        longitude: "23.6025", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "7189", 
        population_proper: "7189",
    }, 
    {
        city: "General Toshevo", 
        latitude: "43.7006", 
        longitude: "28.0367", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "7157", 
        population_proper: "7157",
    }, 
    {
        city: "Devin", 
        latitude: "41.7425", 
        longitude: "24.3992", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "6859", 
        population_proper: "6859",
    }, 
    {
        city: "Kostenets", 
        latitude: "42.3075", 
        longitude: "23.8575", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "6777", 
        population_proper: "6777",
    }, 
    {
        city: "Tvarditsa", 
        latitude: "42.7017", 
        longitude: "25.8975", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sliven", 
        capital: "", 
        population: "6711", 
        population_proper: "6711",
    }, 
    {
        city: "Straldzha", 
        latitude: "42.6000", 
        longitude: "26.6833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Yambol", 
        capital: "", 
        population: "6635", 
        population_proper: "6635",
    }, 
    {
        city: "Varshets", 
        latitude: "43.1953", 
        longitude: "23.2858", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "6500", 
        population_proper: "6500",
    }, 
    {
        city: "Tsarevo", 
        latitude: "42.1708", 
        longitude: "27.8511", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "6196", 
        population_proper: "6196",
    }, 
    {
        city: "Kotel", 
        latitude: "42.8894", 
        longitude: "26.4469", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sliven", 
        capital: "", 
        population: "6021", 
        population_proper: "6021",
    }, 
    {
        city: "Yakoruda", 
        latitude: "42.0183", 
        longitude: "23.6697", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "5813", 
        population_proper: "5813",
    }, 
    {
        city: "Kameno", 
        latitude: "42.5667", 
        longitude: "27.3000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "5788", 
        population_proper: "5788",
    }, 
    {
        city: "Belogradchik", 
        latitude: "43.6269", 
        longitude: "22.6833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "5775", 
        population_proper: "5775",
    }, 
    {
        city: "Elena", 
        latitude: "42.9297", 
        longitude: "25.8772", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "5742", 
        population_proper: "5742",
    }, 
    {
        city: "Vetovo", 
        latitude: "43.7000", 
        longitude: "26.2667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "", 
        population: "5707", 
        population_proper: "5707",
    }, 
    {
        city: "Topolovgrad", 
        latitude: "42.0842", 
        longitude: "26.3375", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "5659", 
        population_proper: "5659",
    }, 
    {
        city: "Bobov Dol", 
        latitude: "42.3661", 
        longitude: "23.0053", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kyustendil", 
        capital: "minor", 
        population: "5651", 
        population_proper: "5651",
    }, 
    {
        city: "Strazhitsa", 
        latitude: "43.2333", 
        longitude: "25.9667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "5589", 
        population_proper: "5589",
    }, 
    {
        city: "Oryahovo", 
        latitude: "43.7367", 
        longitude: "23.9583", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "minor", 
        population: "5367", 
        population_proper: "5367",
    }, 
    {
        city: "Chepelare", 
        latitude: "41.7233", 
        longitude: "24.6861", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "", 
        population: "5262", 
        population_proper: "5262",
    }, 
    {
        city: "Suvorovo", 
        latitude: "43.3300", 
        longitude: "27.5925", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "5214", 
        population_proper: "5214",
    }, 
    {
        city: "Perushtitsa", 
        latitude: "42.0561", 
        longitude: "24.5444", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "5162", 
        population_proper: "5162",
    }, 
    {
        city: "Zlatitudeitsa", 
        latitude: "42.7150", 
        longitude: "24.1389", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "5139", 
        population_proper: "5139",
    }, 
    {
        city: "Bozhurishte", 
        latitude: "42.7500", 
        longitude: "23.2000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "5047", 
        population_proper: "5047",
    }, 
    {
        city: "Polski Trambesh", 
        latitude: "43.3833", 
        longitude: "25.6500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "4980", 
        population_proper: "4980",
    }, 
    {
        city: "Dalgopol", 
        latitude: "43.0500", 
        longitude: "27.3500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "4958", 
        population_proper: "4958",
    }, 
    {
        city: "Sozopol", 
        latitude: "42.4246", 
        longitude: "27.6951", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "minor", 
        population: "4837", 
        population_proper: "4837",
    }, 
    {
        city: "Dolna Banya", 
        latitude: "42.3000", 
        longitude: "23.7667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "4810", 
        population_proper: "4810",
    }, 
    {
        city: "Koynare", 
        latitude: "43.3573", 
        longitude: "24.1450", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "4700", 
        population_proper: "4700",
    }, 
    {
        city: "Trastenik", 
        latitude: "43.5167", 
        longitude: "24.4667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "4560", 
        population_proper: "4560",
    }, 
    {
        city: "Dolni Dabnik", 
        latitude: "43.4089", 
        longitude: "24.4419", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "4548", 
        population_proper: "4548",
    }, 
    {
        city: "Dve Mogili", 
        latitude: "43.6000", 
        longitude: "25.8667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "minor", 
        population: "4463", 
        population_proper: "4463",
    }, 
    {
        city: "Kostandovo", 
        latitude: "42.0167", 
        longitude: "24.1167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "", 
        population: "4456", 
        population_proper: "4456",
    }, 
    {
        city: "Ignatievo", 
        latitude: "43.2500", 
        longitude: "27.7667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "4426", 
        population_proper: "4426",
    }, 
    {
        city: "Shivachevo", 
        latitude: "42.6833", 
        longitude: "26.0333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sliven", 
        capital: "", 
        population: "4387", 
        population_proper: "4387"
    }, 
    {
        city: "Varbitsa", 
        latitude: "42.9931", 
        longitude: "26.6721", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "", 
        population: "4379", 
        population_proper: "4379"
    }, 
    {
        city: "Pravets", 
        latitude: "42.8944", 
        longitude: "23.9156", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "", 
        population: "4363", 
        population_proper: "4363"
    }, 
    {
        city: "Nikopol", 
        latitude: "43.7000", 
        longitude: "24.9000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "minor", 
        population: "4346", 
        population_proper: "4346",
    }, 
    {
        city: "Nedelino", 
        latitude: "41.4556", 
        longitude: "25.0806", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "4339", 
        population_proper: "4339",
    }, 
    {
        city: "Slavyanovo", 
        latitude: "43.4667", 
        longitude: "24.8667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "4335", 
        population_proper: "4335",
    }, 
    {
        city: "Strelcha", 
        latitude: "42.5064", 
        longitude: "24.3211", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "", 
        population: "4277", 
        population_proper: "4277"
    }, 
    {
        city: "Glodzhevo", 
        latitude: "43.7333", 
        longitude: "26.4000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "", 
        population: "4249", 
        population_proper: "4249"
    }, 
    {
        city: "Godech", 
        latitude: "43.0150", 
        longitude: "23.0442", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "minor", 
        population: "4209", 
        population_proper: "4209",
    }, 
    {
        city: "Letnitsa", 
        latitude: "43.3167", 
        longitude: "25.0667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "", 
        population: "4204", 
        population_proper: "4204",
    }, 
    {
        city: "Bratsigovo", 
        latitude: "42.0254", 
        longitude: "24.3709", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "", 
        population: "4072", 
        population_proper: "4072",
    }, 
    {
        city: "Sapareva Banya", 
        latitude: "42.2886", 
        longitude: "23.2642", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kyustendil", 
        capital: "", 
        population: "4060", 
        population_proper: "4060",
    }, 
    {
        city: "Belovo", 
        latitude: "42.2133", 
        longitude: "24.0175", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "", 
        population: "4057", 
        population_proper: "4057",
    }, 
    {
        city: "Breznik", 
        latitude: "42.7400", 
        longitude: "22.9083", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pernik", 
        capital: "", 
        population: "4020", 
        population_proper: "4020",
    }, 
    {
        city: "Smyadovo", 
        latitude: "43.0667", 
        longitude: "27.0167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "", 
        population: "4009", 
        population_proper: "4009",
    }, 
    {
        city: "Rudozem", 
        latitude: "41.4875", 
        longitude: "24.8494", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "3981", 
        population_proper: "3981",
    }, 
    {
        city: "Slivo Pole", 
        latitude: "43.9419", 
        longitude: "26.2064", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "minor", 
        population: "3926", 
        population_proper: "3926",
    }, 
    {
        city: "Zavet", 
        latitude: "43.7667", 
        longitude: "26.6667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Razgrad", 
        capital: "minor", 
        population: "3920", 
        population_proper: "3920",
    }, 
    {
        city: "Debelets", 
        latitude: "43.0438", 
        longitude: "25.6218", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "3907", 
        population_proper: "3907",
    }, 
    {
        city: "Ivaylovgrad", 
        latitude: "41.5281", 
        longitude: "26.1244", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Haskovo", 
        capital: "", 
        population: "3816", 
        population_proper: "3816",
    }, 
    {
        city: "Sarnitsa", 
        latitude: "41.7375", 
        longitude: "24.0243", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "3688", 
        population_proper: "3688",
    }, 
    {
        city: "Marten", 
        latitude: "43.9208", 
        longitude: "26.0819", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "", 
        population: "3672", 
        population_proper: "3672",
    }, 
    {
        city: "Kresna", 
        latitude: "41.7208", 
        longitude: "23.1589", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "3640", 
        population_proper: "3640",
    }, 
    {
        city: "Sungurlare", 
        latitude: "42.7619", 
        longitude: "26.7736", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "3625", 
        population_proper: "3625",
    }, 
    {
        city: "Iskar", 
        latitude: "43.4500", 
        longitude: "24.2667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "3512", 
        population_proper: "3512",
    }, 
    {
        city: "Kran", 
        latitude: "42.6667", 
        longitude: "25.3833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "3501", 
        population_proper: "3501",
    }, 
    {
        city: "Dolna Mitropolia", 
        latitude: "43.4678", 
        longitude: "24.5206", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "", 
        population: "3469", 
        population_proper: "3469",
    }, 
    {
        city: "Primorsko", 
        latitude: "42.2669", 
        longitude: "27.7550", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "minor", 
        population: "3442", 
        population_proper: "3442",
    }, 
    {
        city: "Gulyantsi", 
        latitude: "43.6333", 
        longitude: "24.7000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "minor", 
        population: "3407", 
        population_proper: "3407",
    }, 
    {
        city: "Maglizh", 
        latitude: "42.6083", 
        longitude: "25.5456", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "3371", 
        population_proper: "3371",
    }, 
    {
        city: "Valchedram", 
        latitude: "43.7000", 
        longitude: "23.4500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "3364", 
        population_proper: "3364",
    }, 
    {
        city: "Krivodol", 
        latitude: "43.3667", 
        longitude: "23.4833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "", 
        population: "3346", 
        population_proper: "3346",
    }, 
    {
        city: "Belitsa", 
        latitude: "41.9500", 
        longitude: "23.5667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "3337", 
        population_proper: "3337",
    }, 
    {
        city: "Nikolaevo", 
        latitude: "42.6333", 
        longitude: "25.8000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "3298", 
        population_proper: "3298",
    }, 
    {
        city: "Shabla", 
        latitude: "43.5333", 
        longitude: "28.5333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "3276", 
        population_proper: "3276",
    }, 
    {
        city: "Dragoman", 
        latitude: "42.9189", 
        longitude: "22.9317", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Sofia", 
        capital: "minor", 
        population: "3264", 
        population_proper: "3264",
    }, 
    {
        city: "Kaolinovo", 
        latitude: "43.6167", 
        longitude: "27.0917", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Shumen", 
        capital: "", 
        population: "3227", 
        population_proper: "3227",
    }, 
    {
        city: "Sveti Vlas", 
        latitude: "42.7167", 
        longitude: "27.7667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "3226", 
        population_proper: "3226",
    }, 
    {
        city: "Valchidol", 
        latitude: "43.4000", 
        longitude: "27.5500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "", 
        population: "3218", 
        population_proper: "3218",
    }, 
    {
        city: "Gurkovo", 
        latitude: "42.6606", 
        longitude: "25.7919", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "3207", 
        population_proper: "3207",
    }, 
    {
        city: "Roman", 
        latitude: "43.1500", 
        longitude: "23.9167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "", 
        population: "3131", 
        population_proper: "3131",
    }, 
    {
        city: "Mizia", 
        latitude: "43.6833", 
        longitude: "23.8500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "minor", 
        population: "3126", 
        population_proper: "3126",
    }, 
    {
        city: "Kula", 
        latitude: "43.8833", 
        longitude: "22.5167", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "3110", 
        population_proper: "3110",
    }, 
    {
        city: "Batak", 
        latitude: "41.9425", 
        longitude: "24.2181", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pazardzhik", 
        capital: "minor", 
        population: "3099", 
        population_proper: "3099",
    }, 
    {
        city: "Kalofer", 
        latitude: "42.6111", 
        longitude: "24.9761", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Plovdiv", 
        capital: "", 
        population: "2984", 
        population_proper: "2984",
    }, 
    {
        city: "Pavel Banya", 
        latitude: "42.5972", 
        longitude: "25.2075", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Stara Zagora", 
        capital: "", 
        population: "2922", 
        population_proper: "2922",
    }, 
    {
        city: "Kableshkovo", 
        latitude: "42.6606", 
        longitude: "27.5647", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Burgas", 
        capital: "", 
        population: "2911", 
        population_proper: "2911",
    }, 
    {
        city: "Dolna Oryahovitsa", 
        latitude: "43.1667", 
        longitude: "25.7333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "2884", 
        population_proper: "2884",
    }, 
    {
        city: "Hadzhidimovo", 
        latitude: "41.5161", 
        longitude: "23.8567", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "2839", 
        population_proper: "2839",
    }, 
    {
        city: "Dobrinishte", 
        latitude: "41.8197", 
        longitude: "23.5619", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Blagoevgrad", 
        capital: "", 
        population: "2818", 
        population_proper: "2818",
    }, 
    {
        city: "Yablanitsa", 
        latitude: "43.0250", 
        longitude: "24.1000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Lovech", 
        capital: "", 
        population: "2810", 
        population_proper: "2810",
    }, 
    {
        city: "Loznitsa", 
        latitude: "43.3667", 
        longitude: "26.6000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Razgrad", 
        capital: "", 
        population: "2807", 
        population_proper: "2807",
    }, 
    {
        city: "Zlatitudearitsa", 
        latitude: "43.0442", 
        longitude: "25.8897", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Veliko Tarnovo", 
        capital: "", 
        population: "2753", 
        population_proper: "2753",
    }, 
    {
        city: "Tran", 
        latitude: "42.8348", 
        longitude: "22.6512", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pernik", 
        capital: "minor", 
        population: "2646", 
        population_proper: "2646",
    }, 
    {
        city: "Dospat", 
        latitude: "41.6433", 
        longitude: "24.1589", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "2431", 
        population_proper: "2431",
    }, 
    {
        city: "Bregovo", 
        latitude: "44.1500", 
        longitude: "22.6500", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "2400", 
        population_proper: "2400",
    }, 
    {
        city: "Borovo", 
        latitude: "43.5000", 
        longitude: "25.8000", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "minor", 
        population: "2291", 
        population_proper: "2291",
    }, 
    {
        city: "Boychinovtsi", 
        latitude: "43.4719", 
        longitude: "23.3356", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "1532", 
        population_proper: "1532",
    }, 
    {
        city: "Alfatar", 
        latitude: "43.9500", 
        longitude: "27.2833", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "minor", 
        population: "1447", 
        population_proper: "1447",
    }, 
    {
        city: "Gramada", 
        latitude: "43.8342", 
        longitude: "22.6544", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "1315", 
        population_proper: "1315",
    }, 
    {
        city: "Dimovo", 
        latitude: "43.7500", 
        longitude: "22.7333", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "1107", 
        population_proper: "1107",
    }, 
    {
        city: "Brusartsi", 
        latitude: "43.6667", 
        longitude: "23.0667", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "1094", 
        population_proper: "1094",
    }, 
    {
        city: "Madan", 
        latitude: "41.4987", 
        longitude: "24.9397", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Shiroka Laka", 
        latitude: "41.6793", 
        longitude: "24.5814", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Kirkovo", 
        latitude: "41.3272", 
        longitude: "25.3638", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kardzhali", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Novo Selo", 
        latitude: "44.1586", 
        longitude: "22.7867", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Iskar", 
        latitude: "43.6708", 
        longitude: "24.4523", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Pleven", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Ivanovo", 
        latitude: "43.6857", 
        longitude: "25.9556", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Hayredin", 
        latitude: "43.6019", 
        longitude: "23.6613", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vratsa", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Sitovo", 
        latitude: "44.0273", 
        longitude: "27.0198", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Tsenovo", 
        latitude: "43.5359", 
        longitude: "25.6576", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Ruse", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Byala", 
        latitude: "42.8743", 
        longitude: "27.8886", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Varna", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Borino", 
        latitude: "41.6841", 
        longitude: "24.2930", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Smolyan", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Kaynardzha", 
        latitude: "43.9928", 
        longitude: "27.5071", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Silistra", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Medkovets", 
        latitude: "43.6240", 
        longitude: "23.1688", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Montana", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Drenovets", 
        latitude: "43.6913", 
        longitude: "22.9737", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Ruzhintsi", 
        latitude: "43.6218", 
        longitude: "22.8329", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Spasovo", 
        latitude: "43.7017", 
        longitude: "28.3040", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Krushari", 
        latitude: "43.8167", 
        longitude: "27.7555", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Dobrich", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Boynitsa", 
        latitude: "43.9565", 
        longitude: "22.5326", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Makresh", 
        latitude: "43.7679", 
        longitude: "22.6641", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Chuprene", 
        latitude: "43.5181", 
        longitude: "22.6661", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Vidin", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    }, 
    {
        city: "Nevestino", 
        latitude: "42.2555", 
        longitude: "22.8517", 
        country: "Bulgaria", 
        iso2: "BG", 
        administrative_regions: "Kyustendil", 
        capital: "minor", 
        population: "", 
        population_proper: "",
    },
];